"""
neb_summary.py

Post-process a completed VASP NEB calculation using
output generated by the VTST tools.

Expected VTST files:
    neb.dat
    nebef.dat
    spline.dat
    exts.dat

The script reports:
    - Number of NEB images
    - Initial and final absolute energies
    - Reaction energy
    - Maximum discrete-image barrier
    - VTST spline barrier
    - Reverse barrier

The script also generates:
    - neb_summary.csv
    - neb_profile.png

Usage:
    python3 neb_summary.py

Author: Radha Somaiya
"""

import csv
import os
import re

import matplotlib

# Use a non-interactive backend for HPC/remote systems.
matplotlib.use("Agg")

import matplotlib.pyplot as plt


def read_neb_dat(filename="neb.dat"):
    """
    Read discrete NEB image information from neb.dat.

    Expected columns:
        image
        reaction_coordinate
        relative_energy
        force_related_value
        image_index
    """

    if not os.path.isfile(filename):
        raise FileNotFoundError(
            f"File '{filename}' was not found."
        )

    results = []

    with open(filename, "r") as file:

        for line in file:

            if not line.strip():
                continue

            parts = line.split()

            if len(parts) < 4:
                continue

            try:
                image = int(parts[0])
                reaction_coordinate = float(parts[1])
                relative_energy = float(parts[2])
                force_value = float(parts[3])

            except ValueError:
                continue

            results.append(
                {
                    "image": image,
                    "reaction_coordinate": reaction_coordinate,
                    "relative_energy": relative_energy,
                    "force": force_value,
                }
            )

    if not results:
        raise ValueError(
            "No NEB image data could be read from neb.dat."
        )

    return results


def read_nebef_dat(filename="nebef.dat"):
    """
    Read absolute and relative energies from nebef.dat.

    Expected columns:
        image
        force_related_value
        absolute_energy
        relative_energy
    """

    if not os.path.isfile(filename):
        raise FileNotFoundError(
            f"File '{filename}' was not found."
        )

    results = {}

    with open(filename, "r") as file:

        for line in file:

            if not line.strip():
                continue

            parts = line.split()

            if len(parts) < 4:
                continue

            try:
                image = int(parts[0])

                results[image] = {
                    "force": float(parts[1]),
                    "absolute_energy": float(parts[2]),
                    "relative_energy": float(parts[3]),
                }

            except ValueError:
                continue

    if not results:
        raise ValueError(
            "No NEB energy data could be read from nebef.dat."
        )

    return results


def read_spline_dat(filename="spline.dat"):
    """
    Read the VTST spline data.

    For the VTST spline.dat format used here:

        column 1 = spline/image parameter
        column 2 = reaction coordinate
        column 3 = relative energy
        column 4 = derivative/force-related value

    The NEB energy profile therefore uses:
        x = column 2
        y = column 3
    """

    if not os.path.isfile(filename):
        raise FileNotFoundError(
            f"File '{filename}' was not found."
        )

    reaction_coordinate = []
    relative_energy = []

    with open(filename, "r") as file:

        for line in file:

            if not line.strip():
                continue

            parts = line.split()

            if len(parts) < 3:
                continue

            try:
                x = float(parts[1])
                y = float(parts[2])

            except ValueError:
                continue

            reaction_coordinate.append(x)
            relative_energy.append(y)

    if not reaction_coordinate:
        raise ValueError(
            "No spline data could be read from spline.dat."
        )

    return reaction_coordinate, relative_energy


def read_vtst_extrema(filename="exts.dat"):
    """
    Read extrema reported by VTST from exts.dat.
    """

    if not os.path.isfile(filename):
        return []

    extrema = []

    pattern = re.compile(
        r"Extremum\s+\d+\s+found at image\s+"
        r"([+-]?(?:\d+(?:\.\d*)?|\.\d+)"
        r"(?:[Ee][+-]?\d+)?)"
        r"\s+with energy:\s+"
        r"([+-]?(?:\d+(?:\.\d*)?|\.\d+)"
        r"(?:[Ee][+-]?\d+)?)"
    )

    with open(filename, "r") as file:

        for line in file:

            match = pattern.search(line)

            if match:

                extrema.append(
                    {
                        "position": float(match.group(1)),
                        "energy": float(match.group(2)),
                    }
                )

    return extrema


def combine_results(neb_data, nebef_data):
    """
    Combine reaction-coordinate information from neb.dat
    with absolute energies from nebef.dat.
    """

    combined = []

    for row in neb_data:

        image = row["image"]

        absolute_energy = None

        if image in nebef_data:
            absolute_energy = (
                nebef_data[image]["absolute_energy"]
            )

        combined.append(
            {
                "image": image,
                "reaction_coordinate":
                    row["reaction_coordinate"],
                "absolute_energy":
                    absolute_energy,
                "relative_energy":
                    row["relative_energy"],
                "force":
                    row["force"],
            }
        )

    return combined


def calculate_summary(results, extrema):
    """
    Calculate NEB energetic quantities.
    """

    initial = results[0]
    final = results[-1]

    initial_energy = initial["absolute_energy"]
    final_energy = final["absolute_energy"]

    reaction_energy = (
        final["relative_energy"]
        - initial["relative_energy"]
    )

    maximum_image = max(
        results,
        key=lambda row: row["relative_energy"],
    )

    discrete_barrier = (
        maximum_image["relative_energy"]
        - initial["relative_energy"]
    )

    spline_barrier = None
    spline_position = None

    if extrema:

        maximum_extremum = max(
            extrema,
            key=lambda row: row["energy"],
        )

        spline_barrier = (
            maximum_extremum["energy"]
            - initial["relative_energy"]
        )

        spline_position = (
            maximum_extremum["position"]
        )

    if spline_barrier is not None:

        reverse_barrier = (
            spline_barrier
            - reaction_energy
        )

    else:

        reverse_barrier = (
            discrete_barrier
            - reaction_energy
        )

    return {
        "initial_energy": initial_energy,
        "final_energy": final_energy,
        "reaction_energy": reaction_energy,
        "maximum_image": maximum_image["image"],
        "discrete_barrier": discrete_barrier,
        "spline_barrier": spline_barrier,
        "spline_position": spline_position,
        "reverse_barrier": reverse_barrier,
    }


def save_csv(
    results,
    filename="neb_summary.csv",
):
    """
    Save discrete NEB image data to CSV.
    """

    fieldnames = [
        "Image",
        "Reaction_coordinate",
        "Absolute_energy_eV",
        "Relative_energy_eV",
        "Force",
    ]

    with open(
        filename,
        "w",
        newline="",
    ) as csvfile:

        writer = csv.DictWriter(
            csvfile,
            fieldnames=fieldnames,
        )

        writer.writeheader()

        for row in results:

            writer.writerow(
                {
                    "Image":
                        row["image"],

                    "Reaction_coordinate":
                        f"{row['reaction_coordinate']:.6f}",

                    "Absolute_energy_eV":
                        (
                            f"{row['absolute_energy']:.6f}"
                            if row["absolute_energy"] is not None
                            else ""
                        ),

                    "Relative_energy_eV":
                        f"{row['relative_energy']:.6f}",

                    "Force":
                        f"{row['force']:.6f}",
                }
            )


def plot_neb_profile(
    results,
    spline_x,
    spline_energy,
    filename="neb_profile.png",
):
    """
    Plot the VTST NEB energy profile.

    The continuous curve comes directly from spline.dat.
    The discrete points come from neb.dat.

    No new interpolation is performed in Python.
    """

    image_x = [
        row["reaction_coordinate"]
        for row in results
    ]

    image_energy = [
        row["relative_energy"]
        for row in results
    ]

    fig, ax = plt.subplots(
        figsize=(7, 5)
    )

    ax.plot(
        spline_x,
        spline_energy,
        linewidth=2.0,
        label="VTST spline",
    )

    ax.scatter(
        image_x,
        image_energy,
        s=45,
        zorder=3,
        label="NEB images",
    )

    for row in results:

        ax.annotate(
            str(row["image"]),
            (
                row["reaction_coordinate"],
                row["relative_energy"],
            ),
            xytext=(0, 8),
            textcoords="offset points",
            ha="center",
            fontsize=9,
        )

    ax.set_xlabel(
        "Reaction coordinate"
    )

    ax.set_ylabel(
        "Relative energy (eV)"
    )

    ax.legend(
        frameon=False
    )

    ax.tick_params(
        direction="in",
        top=True,
        right=True,
    )

    fig.tight_layout()

    fig.savefig(
        filename,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)


def print_summary(results, summary):
    """
    Print a compact NEB summary.
    """

    print()

    print(
        f"NEB images:             "
        f"{len(results)}"
    )

    if summary["initial_energy"] is not None:

        print(
            f"Initial energy:         "
            f"{summary['initial_energy']:.6f} eV"
        )

    if summary["final_energy"] is not None:

        print(
            f"Final energy:           "
            f"{summary['final_energy']:.6f} eV"
        )

    print(
        f"Reaction energy:        "
        f"{summary['reaction_energy']:.6f} eV"
    )

    print(
        f"Highest discrete image: "
        f"{summary['maximum_image']}"
    )

    print(
        f"Discrete barrier:       "
        f"{summary['discrete_barrier']:.6f} eV"
    )

    if summary["spline_barrier"] is not None:

        print(
            f"VTST spline barrier:    "
            f"{summary['spline_barrier']:.6f} eV"
        )

        print(
            f"Spline maximum image coordinate: "
            f"{summary['spline_position']:.6f}"
        )

    else:

        print(
            "VTST spline barrier:    "
            "Not available"
        )

    print(
        f"Reverse barrier:        "
        f"{summary['reverse_barrier']:.6f} eV"
    )

    print()

    print(
        "Image data saved to: neb_summary.csv"
    )

    print(
        "NEB profile saved to: neb_profile.png"
    )


def main():
    """
    Main program.
    """

    try:

        neb_data = read_neb_dat(
            "neb.dat"
        )

        nebef_data = read_nebef_dat(
            "nebef.dat"
        )

        spline_x, spline_energy = (
            read_spline_dat(
                "spline.dat"
            )
        )

        extrema = read_vtst_extrema(
            "exts.dat"
        )

        results = combine_results(
            neb_data,
            nebef_data,
        )

        summary = calculate_summary(
            results,
            extrema,
        )

        save_csv(
            results,
            "neb_summary.csv",
        )

        plot_neb_profile(
            results,
            spline_x,
            spline_energy,
            "neb_profile.png",
        )

        print_summary(
            results,
            summary,
        )

    except FileNotFoundError as error:

        print(
            f"Error: {error}"
        )

    except Exception as error:

        print(
            "Error while analyzing VTST NEB results: "
            f"{error}"
        )


if __name__ == "__main__":
    main()
